### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ghost** [unixpickle/atom-pentagons#2]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (C:\Users\Thomas\AppData\Local\atom\app-1.17.0\resources\app\src\text-editor-element.js:68:18)
fixBackgroundColors (C:\Users\Thomas\.atom\packages\pentagons\lib\pentagons.coffee:171:38)
registerBackgroundFixer (C:\Users\Thomas\.atom\packages\pentagons\lib\pentagons.coffee:154:5)
registerEditor (C:\Users\Thomas\.atom\packages\pentagons\lib\pentagons.coffee:115:12)
<unknown> (<embedded>:23081:22)
Function.module.exports.Emitter.simpleDispatch (<embedded>:62314:20)
```

**Comment by unixpickle** [comment]
What version of Atom are you using and where do you see that error? I'm on 1.17.0 and things work fine.

**Comment by ghost** [comment]
All packages / Atom up to date. No visible issues with the actual purpose of the pentagons package, but Deprecation Cop catches it thrice.

Atom: 1.17.0
Pentagons: 0.3.0

**Comment by ghost** [comment]
Perfect! Thanks for the quick response.
